{
 "title": "New dashboard",
 "time": { "from": "2024-02-29T21:00:00.000Z", "to": "2024-04-01T03:36:41.000Z" },
 "panels": [
  {
   "title": "Fare Amount (quantile=0.5)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  fare_amount_quantile\nFROM evidently_metrics \nWHERE\n  $__timeFilter(\"event_time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  share_missing_values\nFROM evidently_metrics \nWHERE\n  $__timeFilter(\"event_time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"event_time\" AS \"time\",\n  prediction_drift\nFROM evidently_metrics\nWHERE\n  $__timeFilter(\"event_time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_time AS \"time\",\n  num_drifted_columns\nFROM evidently_metrics \nWHERE\n  $__timeFilter(\"event_time\")\nORDER BY 1"
    }
   ]
  }
 ]
}